### PR TITLE
switch to plain MIT license

### PR DESCRIPTION
**Pull request by ralphtheninja**

### CODE REVIEW

**Comment by juliangruber** [comment]
+1, but @rvagg should probably +1 this himself

**Comment by ralphtheninja** [comment]
I know that he will :)

**Comment by rvagg** [comment]
you know it :+1:

**Comment by mcollina** [comment]
+1
Il giorno lun 11 mag 2015 alle 09:01 Rod Vagg <notifications@github.com> ha
scritto:

**Pull request merged**
